backend:
  name: git-gateway
  branch: master

media_folder: "static/media"
public_folder: "/media"
locale: "ja"

media_library:
  name: uploadcare
  config:
    # change uploadcare public key
    publicKey: 012e3d35e94b8223b2fc
    multiple: false
    tabs: 'file camera url gphotos instagram evernote flickr'
    effects: 'crop,rotate,mirror,flip,enhance,sharp,blur,grayscale,invert'
    imageShrink: '800x800'
    previewStep: true
    clearable: true
    locale: 'ja'

# Uncomment to leverage Netlify CMS UI authoring flow
# see: https://www.netlifycms.org/docs/configuration-options/#publish-mode
# publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{fields.slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Related Links", name: "relatedLinks", widget: "list"}
      - {label: "Social Image", name: "socialImage", widget: image, required: false }
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Social Image", name: "socialImage", widget: image }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - label: Site Config
            name: siteConfig
            widget: object
            fields:
              - { label: Path Prefix, name: pathPrefix, widget: string, required: true }
              - { label: url, name: url, widget: string, required: true }
              - { label: title, name: title, widget: string, required: true }
              - { label: subtitle, name: subtitle, widget: string, required: true }
              - { label: copyright, name: copyright, widget: string, required: true }
              - { label: disqus Shortname, name: disqusShortname, widget: string, required: false }
              - { label: header Image, name: headerImage, widget: image, required: false }
              - { label: posts Per Page, name: postsPerPage, widget: number, required: true }
              - { label: menu,
                  name: postsPerPage,
                  widget: list,
                  required: false,
                  fields:
                    - { label: label, name: label, widget: string, default: "About me" }
                    - { label: path, name: path, widget: string, default: "/pages/about" }
              }
              - { label: Top Contents,
                  name: topContents,
                  widget: list,
                  required: false,
                  fields:
                    - { label: url, name: url, widget: string, default: "/posts/hoge-hoge" }
              }

              - { label: Social Media Card,
                  name: socialMediaCard,
                  widget: object,
                  fields:
                    - { label: Image, name: image, widget: image, required: false }
              }

              - { label: Author,
                  name: author,
                  widget: object,
                  fields:
                    - { label: name, name: name, widget: string, required: true }
                    - { label: photo, name: photo, widget: string, required: true }
                    - { label: bio, name: bio, widget: string, required: true }
                    - { label: SNS Contacts,
                        name: contracts,
                        widget: object,
                        fields:
                          - { label: email, name: email, widget: string, required: false }
                          - { label: facebook, name: facebook, widget: string, required: false }
                          - { label: twitter, name: twitter, widget: string, required: false }
                          - { label: youtube, name: youtube, widget: string, required: false }
                          - { label: github, name: github, widget: string, required: false }
                          - { label: gitlab, name: gitlab, widget: string, required: false }
                          - { label: codepen, name: codepen, widget: string, required: false }
                          - { label: rss, name: rss, widget: string, required: false, default: "/rss.xml" }
                          - { label: vkontakte, name: vkontakte, widget: string, required: false }
                          - { label: linkedin, name: linkedin, widget: string, required: false }
                          - { label: instagram, name: instagram, widget: string, required: false }
                          - { label: line, name: line, widget: string, required: false }
                          - { label: weibo, name: weibo, widget: string, required: false }
                          - { label: soundcloud, name: soundcloud, widget: string, required: false }
                          - { label: telegram, name: telegram, widget: string, required: false }
                    }
              }

              - { label: Popular View Setting,
                  name: popularView,
                  widget: object,
                  description: "よく読まれているコンテンツのランキングをGoogleAnalyticsから取得するAPI Settingです",
                  fields:
                    - { label: google Analytics Start Date, name: googleAnalyticsStartDate, widget: string, required: true, default: "60daysAgo" }
                    - { label: google Analytics End Date, name: googleAnalyticsEndDate, widget: string, required: true, default: "today" }
                    - { label: google Analytics Metrics, name: googleAnalyticsMetrics, widget: string, required: true, default: "ga:sessions" }
                    - { label: google Analytics Filters Url, name: googleAnalyticsFiltersUrl, widget: string, required: true, default: "/posts/" }
                    - { label: google Analytics Page Size, name: googleAnalyticsPageSize, widget: number, required: true, default: 5 }
              }

          - label: Site Designe
            name: siteDesign
            widget: object
            fields:
              - { label: white, name: white, widget: string, required: true }
              - { label: primary, name: primary, widget: string, required: true }
              - { label: accent, name: accent, widget: string, required: true }
              - { label: base Back, name: baseBack, widget: string, required: true }
              - { label: base Font, name: baseFont, widget: string, required: true }
              - { label: base Gray, name: baseGray, widget: string, required: true }
              - { label: base Gray Light, name: baseGrayLight, widget: string, required: true }
              - { label: rounded, name: rounded, widget: string, required: true }

          - label: Site Secret
            name: secretConfig
            widget: object
            fields:
              - { label: algolia App Id, name: algoliaAppId, widget: string, required: true }
              - { label: algolia Search Api Key, name: algoliaSearchApiKey, widget: string, required: true }
              - { label: algolia Index Name, name: algoliaIndexName, widget: string, required: true }
              - { label: google Adsnse Client Id, name: googleAdsnseClientId, widget: string, required: true }
              - { label: google Adsnse Client Slot, name: googleAdsnseClientSlot, widget: string, required: true }
              - { label: google Analytics Id, name: googleAnalyticsId, widget: string, required: true }
              - { label: google Analytics ViewId, name: googleAnalyticsViewId, widget: string, required: true }
